name: Unity - Build
on: 
  workflow_dispatch:
  push:
    tags:
    - '*'
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Checkout
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v2
        
      # Cache
      - name: Cache repository
        id: cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      
      # Build
      - name: Build project
        id: build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          versioning: Semantic
          customParameters: -Development
          buildName: Accession
          
      # Upload
      - name: Upload build artifact
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: Accession-${{ steps.build.outputs.buildVersion }}-win64
          path: build
          
      # Release
      - name: Create release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build.outputs.buildVersion }}
          release_name: ${{ steps.build.outputs.buildVersion }}
          prerelease: true
          
      # Asset
      - name: Upload release asset
        id: asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: Accession-${{ steps.build.outputs.buildVersion }}-win64.zip
          asset_path: build
          asset_content_type: application/zip
